# Generated by Django 5.2.8 on 2025-11-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0004_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Half', 'Half'), ('Full', 'Full')], default='Full', max_length=20),
        ),
    ]
